### PR TITLE
Add prompt/option for LESS

### PR DESCRIPTION
**Pull request by himynameisdave**
less-is-more

**Language Prompt/LESS Preprocessor Option**
It's sort of been a long time coming because I always set up PLUM-based projects but prefer to use LESS sometimes.

### CODE REVIEW

**Comment by himynameisdave** [comment]
**TODO:** 
- [x] write tests to account for new LESS stuff
- [ ] fix an issue caused when Less tries to `@import` filenames starting with an underscore
- [x] save language to the `.yo-rc.json` file and then use that to reference when running sub-generators

**Comment by jasonbellamy** [comment]
This sounds like a fine idea to me.

**Comment by himynameisdave** [comment]
I'm going to save the language to the config file in this PR (#10)

**Comment by himynameisdave** [comment]
Last thing is that LESS is shitty with `@import`ing things so the underscores will be needed in the `exports` file

**Comment by himynameisdave** [comment]
This maps to the old system (without a `partials/` folder for units and modules), going to re-attempt this in another branch

**Pull request closed without merging**
